# # # # # # # # # # # # # # # # # # 
#  _                              
# | |_   _ __ ___    _   _  __  __
# | __| | '_ ` _ \  | | | | \ \/ /
# | |_  | | | | | | | |_| |  >  < 
#  \__| |_| |_| |_|  \__,_| /_/\_\
#                                
# # # # # # # # # # # # # # # # # # 
#
# config.tmux: standard tmux configuration
source $HOME/.config/tmux/config.tmux

# keybind.tmux: user-defined key bindings
source $HOME/.config/tmux/keybind.tmux

# plugins.tmux: 3rd-party plugins for tmux
source $HOME/.config/tmux/plugins.tmux

# Reources:
# # # # # #
# - cheatsheet: https://gist.github.com/henrik/1967800
