# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  _   _____                                                  _                   _                    _   
# (_) |___ /  __      __  _ __ ___             __ _   _   _  | |_    ___    ___  | |_    __ _   _ __  | |_ 
# | |   |_ \  \ \ /\ / / | '_ ` _ \   _____   / _` | | | | | | __|  / _ \  / __| | __|  / _` | | '__| | __|
# | |  ___) |  \ V  V /  | | | | | | |_____| | (_| | | |_| | | |_  | (_) | \__ \ | |_  | (_| | | |    | |_ 
# |_| |____/    \_/\_/   |_| |_| |_|          \__,_|  \__,_|  \__|  \___/  |___/  \__|  \__,_| |_|     \__|
#                                                                                                          
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

exec --no-startup-id dex --autostart --environment i3

exec --no-startup-id xss-lock --transfer-sleep-lock -- $lock

exec --no-startup-id $comp 

exec --no-startup-id feh --bg-scale ~/images/wallpaper/1920x1080.png

exec --no-startup-id redshift -O 5000
