#  _      _   _     _           
# | | __ (_) | |_  | |_   _   _ 
# | |/ / | | | __| | __| | | | |
# |   <  | | | |_  | |_  | |_| |
# |_|\_\ |_|  \__|  \__|  \__, |
#                          |___/ 
# # # # # # # # # # # # # # # # #

# CONFIG: Window
include window.conf

include font.conf

include input.conf

# CONFIG: THEME
#
# include catppuccin/themes/frappe.conf
#
# include catppuccin/themes/latte.conf
#
# include catppuccin/themes/macchiato.conf

include catppuccin/themes/mocha.conf

# include gruvbox/gruvbox_dark.conf
#
# include gruvbox/gruvbox_dark_hard.conf
#
# include gruvbox/gruvbox_dark_soft.conf
#
# include gruvbox/gruvbox_light.conf
#
# include gruvbox/gruvbox_light_hard.conf
#
# include gruvbox/gruvbox_light_soft.conf
